name: Skunk
on: [push, pull_request]

jobs:
  skunk:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - name: Run Skunk on Project
        run: |
          gem install skunk
          CURRENT_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
          if [[ "$CURRENT_BRANCH" -ne "master" ]]; then
            echo "Executing within branch: $CURRENT_BRANCH"
            skunk lib/
          else
            echo "Executing within master branch"
            skunk lib/ -b master
          fi
